import type { NextPage } from 'next';
import Head from 'next/head';
import ButtonLink from '../components/button-link';
import PageWrapper from '../components/page-wrapper';

const Home: NextPage = () => {
    return (
        <PageWrapper>
            <Head>
                <title>JavaMagi</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div style={{ display: 'flex', justifyContent: 'center' }}>
                <h1
                    style={{
                        textAlign: 'center',
                        width: 'max-content',
                        fontSize: '7rem',
                        marginTop: '10rem',
                    }}
                    className="title"
                >
                    JavaMagi
                </h1>
            </div>
            <p style={{ textAlign: 'center', fontSize: '1.5rem' }}>
                This is a simple app to upload, edit, submit, and automatically judge code
                submissions! Select one of the options below in the menu to proceed. Please note
                that the app is still in its alpha version, so many features are still a work in
                progress and can change at any time!
            </p>
            <div style={{ display: 'flex', justifyContent: 'space-evenly', marginTop: '5rem' }}>
                <ButtonLink href="/problem">Solve a Problem</ButtonLink>
                <ButtonLink className="secondary" href="/create">
                    Create a Problem
                </ButtonLink>
            </div>
        </PageWrapper>
    );
};

export default Home;
